//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public class DataSet
{
    
    public List<DataResult> _results;
    
    public HashSet<DataDimension> _dimensions;
    
    public DataMeasure _measure;
    
    // A result list for data sets
    public virtual List<DataResult> Results
    {
        get
        {
            return _results;
        }
        set
        {
            _results = value;
        }
    }
    
    // An array of data dimensions included in a result set
    public virtual HashSet<DataDimension> Dimensions
    {
        get
        {
            return _dimensions;
        }
        set
        {
            _dimensions = value;
        }
    }
    
    // Information about a measure returned by a data-source
    public virtual DataMeasure Measure
    {
        get
        {
            return _measure;
        }
        set
        {
            _measure = value;
        }
    }
}
